nome = input('Digite nome de  funcionário: ')
empresa = input('Digite a instituição: ')
qtde_funcionarios = int(input('Digite a qtd de funcionarios: '))
mediaMensalidade = float(input('Digite a média da mensalidade: '))
print(nome +' trabalha na empresa '+ empresa)
print('Possui: ', qtde_funcionarios, 'empresa' )
print('A media da mensalidade é de: ' + str(mediaMensalidade))
print('==============VERIQUE OS TIPOS DE DADOS===============')
print('O tipo de dado da variavel [nome] é: ', type(nome))
print('O tipo de dado da variavel [empresa] é: ', type(empresa))
print('O tipo de dado da variavel [qtde_funcionarios] é: ', type(qtde_funcionarios))
print('O tipo de dado da variavel [mediaMensaliudade] é: ', type(mediaMensalidade))

