import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Comparar os elementos das duas Series:")
print("Igual:")
print(ds1 == ds2)
print("Maior:")
print(ds1 > ds2)
print("Menor:")
print(ds1 < ds2)
